Remove usage of tokio-unstable
subspace/subspace-sdk pull request #175
Opened 2023-04-12 14:46 UTC by i1i1

2023-04-12 14:49 UTC, ozgunozerk requested changes
All good!
But I think this is forgotten: https://github.com/subspace/subspace-sdk/blob/master/.github/workflows/push.yml#L24

2023-04-12 15:09 UTC, i1i1 commented
Rebased on top of master

2023-04-12 15:19 UTC, ozgunozerk approved these changes

2023-04-12 15:28 UTC, ozgunozerk requested changes
chacha poly dependency is no longer required afaik.

![image](https://user-images.githubusercontent.com/32795992/231506892-9082c125-d417-47a4-861b-2e9729bd7357.png)

2023-04-12 15:38 UTC, ozgunozerk submitted a review, later dismissed

2023-04-12 16:02 UTC, ozgunozerk submitted a review, later dismissed

2023-04-12 18:05 UTC, ozgunozerk submitted a review, later dismissed

2023-04-13 08:34 UTC, ozgunozerk approved these changes

2023-04-13 08:34 UTC, merged